name: Update Wordle Data and Deploy
permissions:
  contents: write
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  schedule:
    # Runs at 11pm UTC-12 every day
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run update scripts
        run: |
          python scripts/wordle/update_summaries.py
          python scripts/wordle/update_archive.py
          python scripts/wordle/update_guesses_by_round.py
          python scripts/wordle/detect_cheating.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/wordle/
          git commit -m "Update Wordle data" || exit 0
          git push

      # Deploy steps from prod.yml
      - name: Copy data folder
        run: |
          mkdir -p wordle-charts/src/data
          cp -r data/wordle/archive wordle-charts/src/data/
          cp -r data/wordle/summaries wordle-charts/src/data/
          cp -r data/wordle/guesses_by_round/cheating_analysis_normal.json wordle-charts/src/data/
          cp -r data/wordle/guesses_by_round/cheating_analysis_hard.json wordle-charts/src/data/

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 